import ApiService from "@/api/apiClient";
import AllCards from "@/components/AllCards";
import Head from "next/head";
import { useQuery } from "react-query";
import { type ApiData } from "types";

export default function Home() {
  const { data, isLoading, isError, isSuccess } = useQuery<ApiData, Error>(
    ["getCharacters"],
    async () => {
      return await ApiService.getAll();
    }
  );

  const renderResult = () => {
    if (isLoading) {
      return <div>Loading...</div>;
    }
    if (isError) {
      return <div>Something went wrong</div>;
    }
    if (isSuccess) {
      return <AllCards cards={data.results} />;
    }
    return null;
  };

  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          {renderResult()}
        </div>
      </main>
    </>
  );
}
